### ISSUE TITLE
Fix chromosome mouse click behaviour.

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/ideogram#12]
It seems quite doubtful (unnecessary) feature, but should be fixed (or disabled).

**Comment by zeleniy** [comment]
Ok, rotation has been implemented. It look a little differ, but not worse. I hope. Here is example to compare:
https://zeleniy.github.io/ideogram/examples/annotations_external_data.html
http://eweitz.github.io/ideogram/annotations_external_data.html

**Comment by mrouard** [comment]
Thank you.
Is there an easy way to make the chromosome a bit smaller like the original ones?

**Comment by zeleniy** [comment]
Sure, will do

**Comment by zeleniy** [comment]
Done.
