### ISSUE TITLE
Check banana chromosome arm's size

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/ideogram#15]
It seems 10 chromosome arm's looks incorrect - https://zeleniy.github.io/ideogram/examples/polyploid.html

**Comment by mrouard** [comment]
chromosome 1 as well

**Comment by mrouard** [comment]
according to the corrdinates I have generated, the picture should be similar to this one.
![musa_chromosomes](https://cloud.githubusercontent.com/assets/6577109/19191872/7d71ee72-8ca4-11e6-8920-5b481dd1b047.png)

**Comment by zeleniy** [comment]
ok

**Comment by zeleniy** [comment]
@mrouard it seems that data are incorrect. Here is our data file - https://github.com/zeleniy/ideogram/blob/master/data/bands/ncbi/ideogram_banana_v0.1.tsv
Here is a table of lengths of chromosome's left arms. First column is chromosome number, second is length of left arm and third is length of left arm relative to longest left arm. You can see that 2 chromosome's left arm is about 10% of the longest and 11 is about 1% of longest. So may be i incorrect interpret the data you provide or the data incorrect.

P.S. 8 chromosome's left arm is longest, relative length equals to 1 (100%).

| number | length | relative length |
| -------- | ------ | --------------- |
| 1 | 18120000 | 0.63435634 |
| 2 | 2750525 | 0.09629211 |
| 3 | 18743998 | 0.65620165 |
| 4 | 12472018 | 0.43662824 |
| 5 | 14191407 | 0.49682169 |
| 6 | 20087086 | 0.70322132 |
| 7 | 18950865 | 0.66344378 |
| 8 | 28564387 | 1.00000000 |
| 9 | 20800529 | 0.72819798 |
| 10 | 474836 | 0.01662336 |
| 11 | 14119999 | 0.49432179 |

What do you think?

**Comment by mrouard** [comment]
I have edited the table. 2 chromosomes does not look correct ( chr 1 and 10). Can you check?
![picture1](https://cloud.githubusercontent.com/assets/6577109/19630328/f737740c-9988-11e6-9033-281f4fbc05b8.png)
