### ISSUE TITLE
Coloring segment on Ploidy 

### ISSUE THREAD

**Issue by mrouard** [zeleniy/ideogram#18]
How to colour a position range on chromosome. Maybe it is possible to use an edited json format as in homology example.

var config = {
      organism: "banana",
      ploidy: 4,
     ...
      },
var range1 = {
			chr: chr1,  // {'chr1': ['0', '0', '1']},
			start: 6000000,
			stop: 8000000,
                        color: green // {'color': ['0', 'blue', 'green']},
		};

**Comment by zeleniy** [comment]
Here is basic example - https://zeleniy.github.io/ideogram/examples/recombination.html
