### ISSUE TITLE
Introduce polyploid configuration option

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/ideogram#3]

**Comment by zeleniy** [comment]
I have introduced option "ploidy" which on screenshot bellow equals to 3. This is just a base of required functionality.
<img width="1280" alt="screen shot 2016-07-22 at 18 32 26" src="https://cloud.githubusercontent.com/assets/2780617/17062251/3bb67de2-5043-11e6-882d-4509161c88a0.png">

P.S. Later will publish progress on github pages, have a troubles with it now.

**Comment by zeleniy** [comment]
Aha, here is live example - https://zeleniy.github.io/ideogram/examples/polyploid.html
Page code - https://github.com/zeleniy/ideogram/blob/master/examples/polyploid.html

All examples are here - https://zeleniy.github.io/ideogram/examples/

**Comment by mrouard** [comment]
Here are some comments to improve the display @zeleniy 
![ideogram](https://cloud.githubusercontent.com/assets/6577109/18097329/bc2d9f4c-6edd-11e6-9095-e04a872476f1.png)

**Comment by zeleniy** [comment]
It is done. Examples:
* https://zeleniy.github.io/ideogram/examples/polyploid.html
* https://zeleniy.github.io/ideogram/examples/rearrangements.html
