### ISSUE TITLE
Investigate current data format and create one for banana

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/ideogram#5]

**Comment by mrouard** [comment]
the configuration can be done with

"4641": {
      "commonName": "banana",
      "scientificName": "Musa acuminata",
      "scientificNameAbbr": "M. acuminata"}

**Comment by mrouard** [comment]
This is a first TSV draft
[ideogram_banana_v0.1.tsv.txt](https://github.com/zeleniy/ideogram/files/405523/ideogram_banana_v0.1.tsv.txt)

**Comment by zeleniy** [comment]
Ideogram wont work with .js file produced by convert_band_data.py script. I will extent it and write another script which will prepare minimal .js file to draw banana chromosomes.

**Comment by zeleniy** [comment]
Here is PHP script which may convert "custom" TSV files provided above in ideogram specific JSON format.
