### ISSUE TITLE
Fix "histogram" example

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/ideogram#9]
https://zeleniy.github.io/ideogram/examples/annotations_histogram.html

**Comment by zeleniy** [comment]
Fixed.

**Comment by mrouard** [comment]
there is still some problem when clicking on the chromosome. 

The chromosome goes outside the layout of the page (firefox / IE / Chrome) on windows 10

**Comment by zeleniy** [comment]
It will be fixed in #12. The bug affects all examples.
